package com.github.alfu32.sketch.ui

enum class ToolId(val displayName: String) {
    SELECT("Select"),
    AXIAL_GRID("Axial Grid"),
    PLANAR_GRID("Planar Grid"),
    LINE("Line"),
    CONSTRUCTION_LINE("Construction Line"),
    POLYLINE("Polyline"),
    DOUBLE_LINE("Double Line"),
    RIBBON_3D("Ribbon 3D"),
    VOXEL("Voxel"),
    VOXEL_VOLUME("Voxel Volume"),
    VOXEL_FRAME("Voxel Frame"),
    ARCH_WALL("Wall"),
    ARCH_SLAB("Slab"),
    ARCH_STAIR("Stair"),
    ARCH_ADD_HOLE("Add Hole"),
    ARCH_WINDOW_FRAME("Window Frame"),
    ARCH_DOOR_FRAME("Door Frame"),
    HVAC_PLUMBING("HVAC Plumbing"),
    HVAC_VENTILATION("HVAC Ventilation"),
    PRIMITIVE_SPHERE("Sphere"),
    PRIMITIVE_CYLINDER("Cylinder"),
    PRIMITIVE_CONE("Cone"),
    PRIMITIVE_PILL("Pill"),
    MECH_SCREW("Screw"),
    MECH_CIRCULAR_HOLE("Circular Hole"),
    MECH_ROUND_WASHER("Round Washer"),
    MECH_COG_WHEEL("Cog Wheel"),
    FACE_OUTLINE("Face Outline"),
    POLYLINE_MESH("Polyline Mesh"),
    OBJECT_CUT("Cut Objects"),
    SOLID_UNION("Solid Union"),
    SOLID_INTERSECTION("Solid Intersection"),
    SOLID_SUBTRACTION("Solid Subtraction"),
    MESH("Mesh"),
    LINE_OFFSET("Line Offset"),
    CUT_HOLES("Cut Holes"),
    CUT_HOLES_2("Cut Holes 2"),
    CUT_OUT_3("Cutout"),
    EXTRUDE_SWIPE("Extrude Swipe"),
    EXTRUDE_SWIPE_3D("Extrude Swipe 3D"),
    PLANE_SECTION("Plane Section"),
    MESH_INTERSECTION("Mesh Intersection"),
    CUT_WITH_PLANE("Cut With Plane"),
    REVOLVE("Revolve"),
    RECTANGLE("Rectangle"),
    SURFACE_RECTANGLE("Surface Rect"),
    QUAD("Quad"),
    CIRCLE("Circle"),
    LINEAR_DIMENSION("Linear Dimension"),
    TEXT("Text"),
    VECTOR_TEXT("Vector Text"),
    PUSH_PULL("Push/Pull"),
    MOVE("Move"),
    ROTATE("Rotate"),
    ROTATE_2("Rotate 2"),
    SCALE("Scale"),
    STRETCH("Stretch"),
    STRETCH_SCALE("Stretch Scale"),
    RANDOM_OFFSET("Random Offset"),
    ROTATE_STRETCH("Rotate Stretch"),
    COPY_MULTIPLE("Copy Multiple"),
    PLANAR_TRANSLATE_MULTIPLE("Planar Translate Multiple"),
    VOLUMETRIC_TRANSLATE_MULTIPLE("Volumetric Translate Multiple"),
    PLANAR_ROTATE_MULTIPLE("Planar Rotate Multiple"),
    HELICOIDAL_ROTATE_MULTIPLE("Helicoidal Rotate Multiple"),
    ROTATIONAL_ARRAY("Rotational Array"),
    HELICAL_ARRAY("Helical Array"),
    ROTATIONAL_ARRAY_EQUALIZED("Rotational Array Even"),
    HELICAL_ARRAY_EQUALIZED("Helical Array Even"),
    PAINT("Paint"),
    OBJECT_PLACE("Object"),
    PLUGIN("Plugin")
}
