package com.github.alfu32.sketch.ui

enum class ToolId(val displayName: String) {
    SELECT("Select"),
    LINE("Line"),
    CONSTRUCTION_LINE("Construction Line"),
    POLYLINE("Polyline"),
    DOUBLE_LINE("Double Line"),
    VOXEL("Voxel"),
    VOXEL_VOLUME("Voxel Volume"),
    VOXEL_FRAME("Voxel Frame"),
    ARCH_WALL("Wall"),
    ARCH_SLAB("Slab"),
    ARCH_STAIR("Stair"),
    ARCH_ADD_HOLE("Add Hole"),
    ARCH_WINDOW_FRAME("Window Frame"),
    ARCH_DOOR_FRAME("Door Frame"),
    FACE_OUTLINE("Face Outline"),
    LINE_OFFSET("Line Offset"),
    CUT_HOLES("Cut Holes"),
    CUT_HOLES_2("Cut Holes 2"),
    CUT_OUT_3("Cutout"),
    PLANE_SECTION("Plane Section"),
    MESH_INTERSECTION("Mesh Intersection"),
    RECTANGLE("Rectangle"),
    SURFACE_RECTANGLE("Surface Rect"),
    QUAD("Quad"),
    CIRCLE("Circle"),
    LINEAR_DIMENSION("Linear Dimension"),
    TEXT("Text"),
    PUSH_PULL("Push/Pull"),
    MOVE("Move"),
    ROTATE("Rotate"),
    SCALE("Scale"),
    STRETCH("Stretch"),
    PAINT("Paint"),
    OBJECT_PLACE("Object"),
    PLUGIN("Plugin")
}
