#!/bin/bash

INSTALL_PATH="$(cd "$(dirname "$0")" && pwd)"
RUN_PATH="$(pwd)"

if [[ -z "$1" ]]; then
  java -jar "$INSTALL_PATH/katechup3d-editor.jar" edit
  exit $?
fi

case "$1" in
  edit|version|update|help)
    java -jar "$INSTALL_PATH/katechup3d-editor.jar" "$@"
    ;;
  *)
    java -jar "$INSTALL_PATH/katechup3d-editor.jar" edit --file "$1"
    ;;
esac
