#!/bin/bash

INSTALL_PATH="$(cd "$(dirname "$0")" && pwd)"
RUN_PATH="$(pwd)"

if [[ -n "$1" ]]; then
  java -jar "$INSTALL_PATH/katechup3d-editor.jar" --file "$1"
else
  java -jar "$INSTALL_PATH/katechup3d-editor.jar"
fi
