import { copyFile, mkdir, readdir, readFile, rename, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const docsRoot = path.resolve(new URL('..', import.meta.url).pathname);
const repoRoot = path.resolve(docsRoot, '..');
const outputDir = path.join(docsRoot, 'static/images/generated');
const manifestPath = path.join(outputDir, 'manifest.json');
const captureWorkDir = path.join(repoRoot, 'dist/docs-site-captures');
const baseUrl = resolveBaseUrl();
const stepDelayMs = envInt('MCP_STEP_DELAY_MS', 1000);
const pointerPhaseDelayMs = envInt('MCP_POINTER_PHASE_DELAY_MS', 300);
const resetDelayMs = envInt('MCP_RESET_DELAY_MS', 1200);
const consoleDelayMs = envInt('MCP_CONSOLE_DELAY_MS', 1000);
const preCaptureDelayMs = envInt('MCP_PRE_CAPTURE_DELAY_MS', 1600);
const capturePollDelayMs = envInt('MCP_CAPTURE_POLL_DELAY_MS', 250);
const betweenExamplesDelayMs = envInt('MCP_BETWEEN_EXAMPLES_DELAY_MS', 1200);

const requiredActionCommands = [
  'edit.reset_scene_for_capture',
  'tool.builtin.rectangle',
  'tool.builtin.push_pull',
  'tool.builtin.line',
  'tool.builtin.select',
  'edit.group',
  'view.camera.orbit',
  'view.grid_guide',
  'view.lighting',
  'view.capture_ui_minimal',
  'view.capture_ui_restore'
];

const examples = [
  {
    id: 'getting-started-rectangle-face',
    fileName: 'getting-started-rectangle-face.png',
    notes: 'Rectangle face generated by MCP console geometry script for deterministic documentation capture.',
    steps: [
      scriptStep(rectangleFaceScript(-3, -2, 3, 2, 'getting started rectangle face')),
      commandStep('view.camera.orbit')
    ]
  },
  {
    id: 'push-pull-house-solid',
    fileName: 'push-pull-house-solid.png',
    notes: 'Simple solid generated by MCP console geometry script for deterministic documentation capture.',
    steps: [
      scriptStep(boxScript(-3, -2, 3, 2, 4, 'push pull house solid')),
      commandStep('view.camera.orbit')
    ]
  },
  {
    id: 'snapping-midpoint-example',
    fileName: 'snapping-midpoint-example.png',
    notes: 'Line geometry generated by MCP console script for endpoint and midpoint snapping documentation.',
    steps: [
      scriptStep(lineScript(-5, 0, 5, 0, 'snapping midpoint example')),
      optionalCommandStep('view.grid_guide'),
      commandStep('view.camera.orbit')
    ]
  },
  {
    id: 'objects-instance-editing',
    fileName: 'objects-instance-editing.png',
    notes: 'Object-like repeated solids generated by MCP console script; grouping command is discovered and attempted when available.',
    steps: [
      scriptStep(objectsScript()),
      optionalCommandStep('edit.group'),
      commandStep('view.camera.orbit')
    ]
  },
  {
    id: 'lighting-scene-example',
    fileName: 'lighting-scene-example.png',
    notes: 'Small extruded scene generated by MCP console script with the lighting panel command opened when available.',
    steps: [
      scriptStep(boxScript(-2, -2, 2, 2, 4, 'lighting scene example')),
      optionalCommandStep('view.lighting'),
      commandStep('view.camera.orbit')
    ]
  }
];

function resolveBaseUrl() {
  const argIndex = process.argv.findIndex((arg) => arg === '--base-url');
  if (argIndex >= 0 && process.argv[argIndex + 1]) {
    return process.argv[argIndex + 1].replace(/\/$/, '');
  }
  return (process.env.MCP_BASE_URL || 'http://127.0.0.1:8765').replace(/\/$/, '');
}

function envInt(name, fallback) {
  const parsed = Number.parseInt(process.env[name] ?? '', 10);
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : fallback;
}

function commandStep(id) {
  return { kind: 'command', id, optional: false };
}

function optionalCommandStep(id) {
  return { kind: 'command', id, optional: true };
}

function scriptStep(script) {
  return { kind: 'script', script };
}

function rectangleFaceScript(minX, minZ, maxX, maxZ, label) {
  return geometryScript(label, `
    def a = v(${minX}, 0, ${minZ}); def b = v(${maxX}, 0, ${minZ}); def c = v(${maxX}, 0, ${maxZ}); def d = v(${minX}, 0, ${maxZ});
    tri(a, b, c); tri(a, c, d);
    edge(a, b); edge(b, c); edge(c, d); edge(d, a);
  `);
}

function lineScript(minX, z, maxX, targetZ, label) {
  return geometryScript(label, `
    def a = v(${minX}, 0, ${z}); def b = v(${maxX}, 0, ${targetZ});
    edge(a, b);
    edge(v(0, 0, -0.45), v(0, 0, 0.45));
    edge(v(-0.45, 0, 0), v(0.45, 0, 0));
  `);
}

function boxScript(minX, minZ, maxX, maxZ, height, label) {
  return geometryScript(label, `
    def a = v(${minX}, 0, ${minZ}); def b = v(${maxX}, 0, ${minZ}); def c = v(${maxX}, 0, ${maxZ}); def d = v(${minX}, 0, ${maxZ});
    def e = v(${minX}, ${height}, ${minZ}); def f = v(${maxX}, ${height}, ${minZ}); def g2 = v(${maxX}, ${height}, ${maxZ}); def h = v(${minX}, ${height}, ${maxZ});
    tri(a, b, c); tri(a, c, d);
    tri(e, g2, f); tri(e, h, g2);
    tri(a, e, f); tri(a, f, b);
    tri(b, f, g2); tri(b, g2, c);
    tri(c, g2, h); tri(c, h, d);
    tri(d, h, e); tri(d, e, a);
    [ [a,b], [b,c], [c,d], [d,a], [e,f], [f,g2], [g2,h], [h,e], [a,e], [b,f], [c,g2], [d,h] ].each { pair -> edge(pair[0], pair[1]) }
  `);
}

function objectsScript() {
  return geometryScript('objects instance editing', `
    def addBox = { ox ->
      def a = v(ox - 1, 0, -1); def b = v(ox + 1, 0, -1); def c = v(ox + 1, 0, 1); def d = v(ox - 1, 0, 1);
      def e = v(ox - 1, 2, -1); def f = v(ox + 1, 2, -1); def g2 = v(ox + 1, 2, 1); def h = v(ox - 1, 2, 1);
      tri(a, b, c); tri(a, c, d); tri(e, g2, f); tri(e, h, g2);
      tri(a, e, f); tri(a, f, b); tri(b, f, g2); tri(b, g2, c); tri(c, g2, h); tri(c, h, d); tri(d, h, e); tri(d, e, a);
      [ [a,b], [b,c], [c,d], [d,a], [e,f], [f,g2], [g2,h], [h,e], [a,e], [b,f], [c,g2], [d,h] ].each { pair -> edge(pair[0], pair[1]) }
    }
    addBox(-2.5); addBox(2.5);
  `);
}

function geometryScript(label, body) {
  return `def v = { x, y, z -> new com.badlogic.gdx.math.Vector3(x as float, y as float, z as float) }
    def id = { -> java.util.UUID.randomUUID().toString() }
    def g = scene.activeGroup()
    def tri = { a, b, c -> g.faceStore.addTriangle(a, b, c, id()) }
    def edge = { a, b -> g.lineStore.addSegment(a, b, false, id()) }
    ${body}
    g.faceStore.notifyExternalChange()
    g.lineStore.notifyExternalChange()
    status.message = ${groovyString(`Docs capture: ${label}`)}
    null`;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function getJson(pathname) {
  const response = await fetch(`${baseUrl}${pathname}`);
  if (!response.ok) {
    throw new Error(`${pathname} returned ${response.status} ${response.statusText}`);
  }
  return response.json();
}

async function assertMcpRunning(context) {
  const status = await getJson('/mcp/status');
  if (!status.success || !status.running) {
    throw new Error(`MCP stopped while ${context}. Last status: ${JSON.stringify(status)}`);
  }
  return status;
}

async function postText(pathname, body) {
  const response = await fetch(`${baseUrl}${pathname}`, {
    method: 'POST',
    body
  });
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${pathname} returned ${response.status} ${response.statusText}: ${text}`);
  }
  const text = await response.text();
  try {
    return JSON.parse(text);
  } catch (error) {
    if (/"success"\s*:\s*true/.test(text)) {
      return { success: true, raw: text };
    }
    throw error;
  }
}

async function listCommandsWithFallback() {
  try {
    const primary = await getJson('/scene/listCommands');
    const primaryCommands = Array.isArray(primary.commands) ? primary.commands : [];
    if (primaryCommands.length > 0) {
      return { endpoint: '/scene/listCommands', payload: primary, commands: primaryCommands };
    }
  } catch (error) {
    console.warn(`/scene/listCommands failed, trying /scene/commands: ${error.message}`);
  }
  const fallback = await getJson('/scene/commands');
  const fallbackCommands = Array.isArray(fallback.commands) ? fallback.commands : [];
  return { endpoint: '/scene/commands', payload: fallback, commands: fallbackCommands };
}

async function loadManifest() {
  try {
    return JSON.parse(await readFile(manifestPath, 'utf8'));
  } catch {
    return {
      schemaVersion: 1,
      images: [],
      lastMcpProbe: null,
      notes: 'Generated screenshots are produced by local MCP authoring scripts.'
    };
  }
}

async function writeManifest(manifest) {
  await mkdir(path.dirname(manifestPath), { recursive: true });
  await writeFile(`${manifestPath}.tmp`, `${JSON.stringify(manifest, null, 2)}\n`);
  await rename(`${manifestPath}.tmp`, manifestPath);
}

function findCaptureCommands(commands) {
  const pattern = /(screenshot|capture|render.?buffer|render|png)/i;
  return commands.filter((command) => {
    const text = [command.id, command.name, command.description, ...(command.tags ?? [])].join(' ');
    return pattern.test(text);
  });
}

function chooseScreenshotCommand(commands) {
  const discovered = commands.filter((command) => {
    const text = [command.id, command.name, command.description, ...(command.tags ?? [])].join(' ');
    return /(screenshot|render.?buffer|png)/i.test(text);
  });
  return (
    discovered.find((command) => command.id === 'export.screenshot') ??
    discovered.find((command) => /screenshot/i.test(command.id)) ??
    discovered[0] ??
    null
  );
}

function groovyString(value) {
  return `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function commandSet(commands) {
  return new Set(commands.map((command) => command.id));
}

async function executeCommand(id) {
  await assertMcpRunning(`before command ${id}`);
  const response = await getJson(`/scene/command?id=${encodeURIComponent(id)}`);
  if (!response.success) {
    throw new Error(`Command ${id} failed: ${response.message || 'no message'}`);
  }
  await sleep(stepDelayMs);
  await assertMcpRunning(`after command ${id}`);
  return response;
}

async function executeOptionalCommand(id) {
  try {
    return await executeCommand(id);
  } catch (error) {
    console.warn(`Optional command ${id} skipped: ${error.message}`);
    return null;
  }
}

async function pointer(action, x, y, z) {
  await assertMcpRunning(`before pointer ${action}`);
  const query = new URLSearchParams({
    action,
    worldX: String(x),
    worldY: String(y),
    worldZ: String(z)
  });
  const response = await getJson(`/scene/pointer?${query.toString()}`);
  if (!response.success) {
    throw new Error(`Pointer ${action} at ${x},${y},${z} failed: ${response.message || 'no message'}`);
  }
  await sleep(pointerPhaseDelayMs);
  await assertMcpRunning(`after pointer ${action}`);
}

async function clickWorld(x, y, z) {
  await pointer('move', x, y, z);
  await sleep(pointerPhaseDelayMs);
  await pointer('down', x, y, z);
  await sleep(pointerPhaseDelayMs);
  await pointer('up', x, y, z);
}

async function setCaptureSaveFile(exampleId) {
  const savePath = path.join(captureWorkDir, `${exampleId}.octd`);
  const script = `save.set(${groovyString(savePath)})`;
  await assertMcpRunning(`before save path script for ${exampleId}`);
  const response = await postText('/scene/console', script);
  if (!response.success) {
    throw new Error(`Could not set capture save file: ${response.message || JSON.stringify(response)}`);
  }
  await sleep(consoleDelayMs);
  await assertMcpRunning(`after save path script for ${exampleId}`);
  return { savePath, script };
}

async function executeConsoleScript(script, label) {
  await assertMcpRunning(`before console script ${label}`);
  const response = await postText('/scene/console', script);
  if (!response.success) {
    throw new Error(`Console script ${label} failed: ${response.message || response.raw || JSON.stringify(response)}`);
  }
  await sleep(consoleDelayMs);
  await assertMcpRunning(`after console script ${label}`);
  return response;
}

async function latestPng(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const pngFiles = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.toLowerCase().endsWith('.png')) {
      continue;
    }
    const file = path.join(directory, entry.name);
    const info = await stat(file);
    pngFiles.push({ file, mtimeMs: info.mtimeMs });
  }
  pngFiles.sort((a, b) => b.mtimeMs - a.mtimeMs);
  return pngFiles[0]?.file ?? null;
}

function screenshotPathFromResponse(response) {
  const text = [
    response.stdout,
    response.message,
    ...(Array.isArray(response.stdoutLines) ? response.stdoutLines : [])
  ].join('\n');
  const matches = text.match(/(?:[A-Za-z]:\\|\/)[^"\n\r]+?\.png/g);
  return matches?.at(-1) ?? null;
}

async function capturePng(screenshotCommandId, beforePath) {
  await sleep(preCaptureDelayMs);
  const response = await executeCommand(screenshotCommandId);
  const pathFromResponse = screenshotPathFromResponse(response);
  if (pathFromResponse) {
    try {
      await stat(pathFromResponse);
      return { sourcePath: pathFromResponse, response };
    } catch {
      // Fall back to mtime probing below.
    }
  }
  for (let attempt = 0; attempt < 50; attempt += 1) {
    const candidate = await latestPng(captureWorkDir);
    if (candidate && candidate !== beforePath) {
      return { sourcePath: candidate, response };
    }
    await sleep(capturePollDelayMs);
  }
  throw new Error(`Screenshot command ${screenshotCommandId} completed but no PNG file was found.`);
}

async function runExample(example, commands, screenshotCommand) {
  const availableCommands = commandSet(commands);
  const commandsUsed = [];
  const scriptsUsed = [];
  await executeCommand('edit.reset_scene_for_capture');
  commandsUsed.push('edit.reset_scene_for_capture');
  await sleep(resetDelayMs);
  await executeOptionalCommand('view.capture_ui_minimal');
  if (availableCommands.has('view.capture_ui_minimal')) {
    commandsUsed.push('view.capture_ui_minimal');
  }
  const { script } = await setCaptureSaveFile(example.id);
  scriptsUsed.push(script);

  for (const step of example.steps) {
    if (step.kind === 'command') {
      if (!availableCommands.has(step.id)) {
        if (step.optional) {
          console.warn(`Optional command ${step.id} is not present in this build.`);
          continue;
        }
        throw new Error(`Required command ${step.id} is not present in this build.`);
      }
      if (step.optional) {
        await executeOptionalCommand(step.id);
      } else {
        await executeCommand(step.id);
      }
      commandsUsed.push(step.id);
      await sleep(stepDelayMs);
    } else if (step.kind === 'pointer') {
      if (step.action === 'click') {
        await clickWorld(step.x, step.y, step.z);
      } else {
        await pointer(step.action, step.x, step.y, step.z);
      }
      await sleep(stepDelayMs);
    } else if (step.kind === 'script') {
      await executeConsoleScript(step.script, example.id);
      scriptsUsed.push(step.script);
      await sleep(stepDelayMs);
    }
  }

  const beforePath = await latestPng(captureWorkDir);
  const { sourcePath } = await capturePng(screenshotCommand.id, beforePath);
  commandsUsed.push(screenshotCommand.id);
  const targetPath = path.join(outputDir, example.fileName);
  await copyFile(sourcePath, targetPath);

  return {
    id: example.id,
    file: `/images/generated/${example.fileName}`,
    source: 'mcp-render-buffer',
    generatedAt: new Date().toISOString(),
    appTarget: 'desktop',
    commandsUsed,
    scriptUsed: scriptsUsed.join('\n\n'),
    notes: `${example.notes} Source capture: ${sourcePath}. Capture pacing: step=${stepDelayMs}ms, reset=${resetDelayMs}ms, console=${consoleDelayMs}ms, preCapture=${preCaptureDelayMs}ms.`
  };
}

function upsertImageRecord(manifest, record) {
  const images = Array.isArray(manifest.images) ? manifest.images : [];
  const index = images.findIndex((image) => image.id === record.id);
  if (index >= 0) {
    images[index] = record;
  } else {
    images.push(record);
  }
  manifest.images = images.sort((a, b) => a.id.localeCompare(b.id));
}

async function main() {
  await mkdir(outputDir, { recursive: true });
  await mkdir(captureWorkDir, { recursive: true });

  const status = await assertMcpRunning('starting capture script');

  const catalog = await listCommandsWithFallback();
  const commands = catalog.commands;
  const captureCommands = findCaptureCommands(commands);
  const screenshotCommand = chooseScreenshotCommand(commands);
  const manifest = await loadManifest();
  manifest.lastMcpProbe = {
    generatedAt: new Date().toISOString(),
    baseUrl,
    status,
    commandEndpoint: catalog.endpoint,
    commandCount: commands.length,
    likelyCaptureCommands: captureCommands.map((command) => ({
      id: command.id,
      name: command.name,
      description: command.description,
      tags: command.tags ?? []
    }))
  };
  manifest.notes =
    'Generated screenshots are real captures from local MCP automation. The script discovers capture commands at runtime and currently prefers the framebuffer-backed screenshot command when present.';

  if (!screenshotCommand) {
    await writeManifest(manifest);
    throw new Error('No screenshot/render-buffer capture command was discovered. Use a documented window/browser screenshot fallback.');
  }

  const missingRequired = requiredActionCommands.filter((id) => !commands.some((command) => command.id === id));
  if (missingRequired.length > 0) {
    console.warn(`Commands not present in this build: ${missingRequired.join(', ')}`);
  }

  const records = [];
  for (const example of examples) {
    const record = await runExample(example, commands, screenshotCommand);
    upsertImageRecord(manifest, record);
    records.push(record);
    console.log(`Captured ${example.fileName}`);
    await sleep(betweenExamplesDelayMs);
  }
  await executeOptionalCommand('view.capture_ui_restore');
  await writeManifest(manifest);
  console.log(`Wrote ${records.length} generated screenshot manifest record(s).`);
}

main().catch((error) => {
  console.error(`MCP capture failed: ${error.message}`);
  console.error('Start Octodraw locally, enable MCP, and retry with --base-url http://127.0.0.1:8765.');
  process.exit(1);
});
